### ISSUE TITLE
[Feature] Use session keys

### ISSUE THREAD

**Issue by CodeAlDente** [cs-eliseev/helpers-session#1]
I would suggest to work with session keys, e.g. instead of using `$_SESSION["foobar"]` it should be `$_SESSION[$session_key]["foobar"]`. The benefit of this is that we do not touch any other sessions which might not be related to the application itself and both, other sessions and sessions by the application can coexist - in peace and harmony. :wink:

**Comment by cs-eliseev** [comment]
Honestly, it is strange if the application has a key conflict, which means that the developer does not know his application ...

**Comment by CodeAlDente** [comment]
> which means that the developer does not know his application ...

Fair point but I am using the session handler to deal with various things. From authentication to validating form requests by using a csrf protection. There are also some sessions that keep track of the users activity. So I do not want to lose any of those information by mistake. The best way would be to use keys to differ authentication sessions from the others.

**Comment by cs-eliseev** [comment]
Will it be convenient:
```php
Seesion::setGlobalKey('global_key');
Session::set('foobar', 'example_value');
// $_SESSION['global_key']['foobar'] -> 'example_value'

Session::has('foobar');
// $_SESSION['global_key']['foobar'] -> true

Session::get('foobar');
// $_SESSION['global_key']['foobar'] -> 'example_value'

Session::remove('foobar');
// $_SESSION['global_key']['foobar'] -> null

Seesion::setGlobalKey();
Session::set('foobar', 'example_value');
// $_SESSION['foobar'] -> 'example_value'

Session::has('foobar');
// $_SESSION['foobar'] -> true

Session::get('foobar');
// $_SESSION['foobar'] -> 'example_value'

Session::remove('foobar');
// $_SESSION['foobar'] -> null
```

??? =)

**Comment by CodeAlDente** [comment]
Yes that would be perfect. :+1: But why not just `setKey()`?

**Comment by cs-eliseev** [comment]
Add new method:
* setMultiKey - global key $_SESSION[$multiKey]
* all - get all session data ($_SESSION | $_SESSION[$multiKey])
* clear - clear session data ($_SESSION | $_SESSION[$multiKey])
* destroy - destroy session
* isStart - check start session
* update all method use $multiKey ($_SESSION | $_SESSION[$multiKey])
* update examples-session.php
* update unit test

Tommorow:
* add example to README;
* update realise minor version

**Comment by cs-eliseev** [comment]
update release 1.1.0
