### ISSUE TITLE
[Feature] Clear all session data

### ISSUE THREAD

**Issue by CodeAlDente** [cs-eliseev/helpers-session#2]
A method called `clear()` would be perfect to ~delete~ [destroy](session_destroy) every session.

**Comment by cs-eliseev** [comment]
Method clear, use remove all session data?

**Comment by CodeAlDente** [comment]
Yes, to delete every session. Otherwise we need to delete every single session.

**Comment by cs-eliseev** [comment]
I add 2 method:
* destroy
* delete

Delete, use cycle unset key Session.

**Comment by CodeAlDente** [comment]
I think `destroy()` is perfectly fine as it could check if there has been set a key and if so, it could just delete the session containing this key. Otherwise it could just call `session_destroy()` to delete every session.

**Comment by cs-eliseev** [comment]
Add new method:
* setMultiKey - global key $_SESSION[$multiKey]
* all - get all session data ($_SESSION | $_SESSION[$multiKey])
* clear - clear session data ($_SESSION | $_SESSION[$multiKey])
* destroy - destroy session
* isStart - check start session
* update all method use $multiKey ($_SESSION | $_SESSION[$multiKey])
* update examples-session.php
* update unit test

Tommorow:
* add example to README;
* update realise minor version

**Comment by cs-eliseev** [comment]
update release 1.1.0
